version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-2)
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
      - docker images
      - echo Building the Docker image..        
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
artifacts:
  files:
    - target/springDockerTest.jar 
